version: '2.4'
services:
  dj:
    # build:
    #   context: ..
    #   dockerfile: ./ubuntu/Dockerfile
    #   args:
    #     UBUNTU_VER: $UBUNTU_VER
    image: datajoint/pydev:${PY_VER}-ubuntu${UBUNTU_VER}
    environment:
      - DISPLAY
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=datajoint
    command: jupyter notebook
    user: 1000:1000
    ports:
      - "8888:8888"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
